Con tag

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -2,52 +2,48 @@ name: Docker Image CI
 
 on:
   push:
-    branches: [ "main" ]
-  pull_request:
-    branches: [ "main" ]
+    tags:
+      - "v*.*.*" # Se ejecuta cuando hay un push con tags semánticos como v1.0.0
+    branches:
+      - "main"   # Opcional: También puede ejecutarse en la rama main
 
 jobs:
-
   build:
-
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+    # 1. Checkout del repositorio
+    - name: Checkout
+      uses: actions/checkout@v4
       with:
         fetch-depth: 0
-    - name: Docker meta
-      id: meta
-      uses: docker/metadata-action@v5
-      with:
-        images: |
-          esrora/docker-prueba   
-        tags: |
-          type=schedule
-          type=ref,event=branch
-          type=ref,event=pr
-          type=semver,pattern={{version}}
-          type=semver,pattern={{major}}.{{minor}}
-          type=semver,pattern={{major}}
-          type=sha            
 
-    - name: Login to Docker Hub
-      if: github.event_name != 'pull_request'
-      uses: docker/login-action@v3
-      with:
-          username: ${{ secrets.DOCKER_USER }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+    # 2. Obtener el tag del commit actual
+    - name: Get the current tag
+      id: versioning
+      run: |
+        # Obtener el tag actual asociado al commit
+        TAG=$(git describe --tags --exact-match 2>/dev/null || echo "no-tag")
+        if [ "$TAG" = "no-tag" ]; then
+          echo "Error: Este commit no tiene un tag asociado. Por favor, etiqueta el commit antes de continuar."
+          exit 1
+        fi
+        echo "TAG=$TAG" >> $GITHUB_ENV
+        echo "El tag actual es: $TAG"
 
-    - name: Set up QEMU
-      uses: docker/setup-qemu-action@v3
+    # 3. Login en Docker
+    - name: Docker login
+      env:
+        DOCKER_USER: ${{ secrets.DOCKER_USER }}
+        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      run: |
+        echo "Iniciando login…."
+        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
+        echo "Fin del login"
 
-    - name: Set up Docker Buildx
-      uses: docker/setup-buildx-action@v3
-
-    - name: Build and push
-      uses: docker/build-push-action@v6
-      with:
-        push: ${{ github.event_name != 'pull_request' }}
-        tags: ${{ steps.meta.outputs.tags }}
-        labels: ${{ steps.meta.outputs.labels }}
+    # 4. Construir y etiquetar la imagen Docker
+    - name: Build and tag Docker image
+      run: |
+        docker build -t esrora/docker-prueba:${{ env.TAG }} .
+        docker build -t esrora/docker-prueba:latest .
+        docker push esrora/docker-prueba:${{ env.TAG }}
+        docker push esrora/docker-prueba:latest
